apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openfaas-ingress
  namespace: openfaas
  annotations:
    # nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.auth.svc.cluster.local/oauth2/auth"
    # nginx.ingress.kubernetes.io/auth-signin: "http://openfaas.local/oauth2/start?rd=$escaped_request_uri"
     # Enable JWT validation
    nginx.ingress.kubernetes.io/auth-jwt: "on"

    # JWKS endpoint (public keys)
    nginx.ingress.kubernetes.io/auth-jwt-key: "http://keycloak.auth.svc.cluster.local:8080/realms/openfaas/protocol/openid-connect/certs"

    # Issuer must match `iss` claim in token
    nginx.ingress.kubernetes.io/auth-jwt-issuer: "http://keycloak.local/realms/openfaas"

    # Require Authorization header
    nginx.ingress.kubernetes.io/auth-jwt-header: "Authorization"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32K"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "24k"
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization"
    nginx.ingress.kubernetes.io/auth-method: "GET"
    nginx.ingress.kubernetes.io/auth-pass-request-headers: "Authorization"
spec:
  ingressClassName: nginx
  rules:
  - host: openfaas.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gateway
            port:
              number: 8080
